export { default as Home } from './Home'
export { default as Detail } from './Detail'
export { default as Favs } from './Favs'
export { default as User } from './User'
export { default as NotRegisteredUser } from './NotRegisteredUser'
